// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphqlv1

type Mutation struct {
}

type Query struct {
}

// User request data structure
type UserRequest struct {
	ID    *int32 `json:"id,omitempty"`
	Name  string `json:"name"`
	Email string `json:"email"`
	Phone string `json:"phone"`
	Age   int32  `json:"age"`
}

// User response data structure
type UserResponse struct {
	ID    int32  `json:"id"`
	Name  string `json:"name"`
	Email string `json:"email"`
	Phone string `json:"phone"`
	Age   int32  `json:"age"`
}
