services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: micro
      MYSQL_USER: micro
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
#    volumes:
#      - ./volumes/data/mysql/:/var/lib/mysql
