// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package v1

// User creation data structure
type CreateUser struct {
	Name  string `json:"name"`
	Email string `json:"email"`
	Phone string `json:"phone"`
	Age   int32  `json:"age"`
}

type Mutation struct {
}

type Query struct {
}

// User updating data structure
type UpdateUser struct {
	ID    int32  `json:"id"`
	Name  string `json:"name"`
	Email string `json:"email"`
	Phone string `json:"phone"`
	Age   int32  `json:"age"`
}

// User response data structure
type User struct {
	ID    int32  `json:"id"`
	Name  string `json:"name"`
	Email string `json:"email"`
	Phone string `json:"phone"`
	Age   int32  `json:"age"`
}
