// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: v1/greeter_api.proto

package hellov1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GreeterAPI_GetHello_FullMethodName = "/hello.v1.GreeterAPI/GetHello"
)

// GreeterAPIClient is the client API for GreeterAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Service for greeting persons
type GreeterAPIClient interface {
	// Get hello message
	GetHello(ctx context.Context, in *GetHelloRequest, opts ...grpc.CallOption) (*GetHelloResponse, error)
}

type greeterAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewGreeterAPIClient(cc grpc.ClientConnInterface) GreeterAPIClient {
	return &greeterAPIClient{cc}
}

func (c *greeterAPIClient) GetHello(ctx context.Context, in *GetHelloRequest, opts ...grpc.CallOption) (*GetHelloResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetHelloResponse)
	err := c.cc.Invoke(ctx, GreeterAPI_GetHello_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GreeterAPIServer is the server API for GreeterAPI service.
// All implementations should embed UnimplementedGreeterAPIServer
// for forward compatibility.
//
// Service for greeting persons
type GreeterAPIServer interface {
	// Get hello message
	GetHello(context.Context, *GetHelloRequest) (*GetHelloResponse, error)
}

// UnimplementedGreeterAPIServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGreeterAPIServer struct{}

func (UnimplementedGreeterAPIServer) GetHello(context.Context, *GetHelloRequest) (*GetHelloResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetHello not implemented")
}
func (UnimplementedGreeterAPIServer) testEmbeddedByValue() {}

// UnsafeGreeterAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GreeterAPIServer will
// result in compilation errors.
type UnsafeGreeterAPIServer interface {
	mustEmbedUnimplementedGreeterAPIServer()
}

func RegisterGreeterAPIServer(s grpc.ServiceRegistrar, srv GreeterAPIServer) {
	// If the following call pancis, it indicates UnimplementedGreeterAPIServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GreeterAPI_ServiceDesc, srv)
}

func _GreeterAPI_GetHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterAPIServer).GetHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GreeterAPI_GetHello_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterAPIServer).GetHello(ctx, req.(*GetHelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GreeterAPI_ServiceDesc is the grpc.ServiceDesc for GreeterAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GreeterAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "hello.v1.GreeterAPI",
	HandlerType: (*GreeterAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetHello",
			Handler:    _GreeterAPI_GetHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "v1/greeter_api.proto",
}
